inherit_from: http://relaxed.ruby.style/rubocop.yml

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/IndentationWidth:
  Exclude:
    - 'lib/rbexec.rb'

Layout/IndentHash:
  Exclude:
    - 'lib/rbexec.rb'

Lint/UnneededSplatExpansion:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Exclude:
    - 'lib/rbexec.rb'

Style/ExpandPathArguments:
  Enabled: false

Style/FlipFlop:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/SymbolArray:
  Enabled: false
