language: ruby
dist: trusty
cache: bundler
addons:
  apt:
    packages:
      - bash
      - ash
      - dash
      - ksh
      - mksh
      - pdksh
      - zsh
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
